---
- hosts: all
  roles:

  # osx config
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    packages:
      - font-source-code-pro
      - font-sauce-code-powerline

  # cli
  - role: oh_my_zsh
  - role: homeshick
    repo: git@bitbucket.org:nettabo/dotfiles.git

  # Homebrew
  - role: brew_package
    packages:
      - wget
      - git
      - tig
  - role: brew_package
    tap: peco/peco
    package_name: peco

  # Homebrew Cask
  - role: cask_package
    packages:
      - atom
      - iterm2
      - karabiner
      - dropbox

