---
- hosts: all
  roles:

  # osx config
  - role: dashboard
    disabled: YES

  # fonts
  #- role: cask_package
  #  tap: caskroom/fonts
  #  package_name: font-source-code-pro
  #- role: cask_package
  #  tap: caskroom/fonts
  #  package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: oh_my_zsh
  - role: brew_package
    package_name: wget
  - role: brew_package
    package_name: tig
  - role: brew_package
    tap: peco/peco
    package_name: peco
  ## languages
  #- role: git_package
  #  repo: riywo/anyenv
  #- role: npm_package
  #  package_name: grunt
  #- role: npm_package
  #  package_name: bower
  ## databases
  #- role: brew_package
  #  package_name: mongodb
  ## deployment
  #- role: brew_package
  #  package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  ## terminal
  - role: cask_package
    package_name: iterm2
  ## keyboard
  - role: cask_package
    package_name: karabiner

