---
- hosts: all
  roles:

  # osx config
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    packages:
      - font-source-code-pro
      - font-sauce-code-powerline

  # themes
  - role: git_package
    remote_repo: github.com/larssmit/iterm2-getafe
    local_repo: ~/src/github.com/larssmit/iterm2-getafe

  # cli
  - role: oh_my_zsh
  - role: homeshick
    repo: git@bitbucket.org:nettabo/dotfiles.git
  - role: neobundle

  # gui
  - role: alfred

  # Homebrew
  - role: brew_package
    packages:
      - wget
      - git
      - tig
      - go
  - role: brew_package
    tap: peco/peco
    package_name: peco
  - role: brew_package
    tap: motemen/ghq
    package_name: ghq

  # Homebrew Cask
  - role: cask_package
    packages:
      - atom
      - iterm2
      - karabiner
      - dropbox

